version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - db
      - devdb
    image: 'nodejs'
    container_name: app
    restart: unless-stopped
    env_file: .env
    ports: 
      - "8085:8085"
    volumes: 
      - .:/app
      - node_modules:/node_modules
    networks: 
      - app-network
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    ports: 
      - 5432:5432
    env_file: .env
    environment: 
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes: 
      - dbdata:/data/db
    networks: 
      - app-network
  devdb:
    image: postgres
    container_name: devdb
    restart: unless-stopped
    ports: 
      - 5434:5434
    env_file: .env
    environment: 
      - POSTGRES_DB=$DEV_POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes: 
      - dbdata:/data/devdb
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge

volumes: 
  dbdata:
  node_modules: